sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    Note right of browser: The browser send JSON data to the server
    activate server
    Note right of server: The server processes the data it received and store's it on the data.json file
    server-->>browser: Send a message the note is created
    deactivate server

    Note right of browser: The browser updates the notes on the page without reload
